import { ScenarioState } from './types';

export const DEFAULT_SCENARIO: ScenarioState = {
  startDate: 'sep15',
  trailing90: 0,
  leads: 1_000_000,
  wordsPerOutbound: 20,
  conversationsPerLead: 1,
  outboundPerConversation: 2,
  inboundPerConversation: 2,
  rcsAdoption: 0.6,
  mmsShare: 0.2,
  tollFreeShare: 0.3,
  verifyAttemptsPerLead: 0.5,
  verifySuccessRate: 0.9,
  aiRepliesPerConversation: 1,
  lookupsPerLead: 0.2,
  callsPerLead: 0.1,
  minutesPerCall: 4,
  campaignsActive: 3,
  askTierA: 32,
  askTierB: 37,
  askTierC: 45,
  engagementRate: 19,
  conversionRate: 1.0,
  revenuePerSale: 120,
  projectionStartSpend: 100000,
  projectionGrowth: 13.1,
  projectionMonths: 24,
};
